/* Generated by cbindgen from crates/vt-ffi. Do not edit; run `mise run abi:update`. */

#ifndef VT_FFI_H
#define VT_FFI_H

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * ABI version. Bumped on every incompatible change to any exported type
 * or function; Swift asserts equality at startup.
 */
#define VtVT_FFI_ABI_VERSION 1

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Returns [`VT_FFI_ABI_VERSION`] so the Swift side can refuse a mismatched
 * static library before touching any other symbol.
 */
uint32_t vt_ffi_abi_version(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* VT_FFI_H */
